"use client";
import Link from "next/link";
import {FormEvent,KeyboardEvent,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {usePreferences} from "@/components/preferences-provider";
import {portalCopy} from "@/lib/portal-i18n";
import {getCsrfToken} from "@/lib/security/csrf-client";

type Action="change_profile"|"change_password"|"delete_account";
function strength(value:string){const checks=[value.length>=12,/[a-z]/.test(value),/[A-Z]/.test(value),/\d/.test(value),/[^A-Za-z0-9\s]/.test(value)];return{checks,score:checks.filter(Boolean).length,valid:checks.every(Boolean)}}
export function AccountSettings({email,initialName,initialUsername}:{email:string;initialName:string;initialUsername:string}){
 const{locale,text}=usePreferences();const t=portalCopy[locale].settings;const router=useRouter();
 const[name,setName]=useState(initialName);const[username,setUsername]=useState(initialUsername);const[password,setPassword]=useState("");const[repeat,setRepeat]=useState("");const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);const[action,setAction]=useState<Action|null>(null);const[digits,setDigits]=useState(Array(6).fill(""));const inputs=useRef<Array<HTMLInputElement|null>>([]);const pw=useMemo(()=>strength(password),[password]);
 async function requestCode(next:Action){setBusy(true);setStatus("");try{const csrf=await getCsrfToken();const response=await fetch("/api/account/security/request",{method:"POST",headers:{"Content-Type":"application/json","x-voidworks-csrf":csrf},credentials:"same-origin",body:JSON.stringify({action:next,locale})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error==="RATE_LIMIT"?text.auth.rateLimit:t.failed);setAction(next);setDigits(Array(6).fill(""));setTimeout(()=>inputs.current[0]?.focus(),80);}catch(e){setStatus(e instanceof Error?e.message:t.failed);}finally{setBusy(false)}}
 function digit(i:number,v:string){const x=v.replace(/\D/g,"").slice(-1);setDigits(cur=>{const n=[...cur];n[i]=x;return n});if(x&&i<5)inputs.current[i+1]?.focus()}
 function key(i:number,e:KeyboardEvent<HTMLInputElement>){if(e.key==="Backspace"&&!digits[i]&&i>0)inputs.current[i-1]?.focus()}
 function paste(v:string){const clean=v.replace(/\D/g,"").slice(0,6);setDigits(Array.from({length:6},(_,i)=>clean[i]||""));inputs.current[Math.max(0,Math.min(clean.length,6)-1)]?.focus()}
 async function confirm(e:FormEvent){e.preventDefault();if(!action)return;const code=digits.join("");if(!/^\d{6}$/.test(code)){setStatus(t.invalidCode);return}setBusy(true);setStatus("");try{const csrf=await getCsrfToken();const payload:Record<string,unknown>={action,code};if(action==="change_profile"){payload.fullName=name;payload.username=username}if(action==="change_password")payload.password=password;const response=await fetch("/api/account/security/confirm",{method:"POST",headers:{"Content-Type":"application/json","x-voidworks-csrf":csrf},credentials:"same-origin",body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));if(!response.ok){if(result.error==="USERNAME_TAKEN")throw new Error(t.usernameTaken);if(["INVALID_CODE","CODE_EXPIRED","CODE_LOCKED"].includes(result.error))throw new Error(t.invalidCode);throw new Error(t.failed)}setAction(null);if(result.deleted){window.location.href="/register";return}if(result.logout){window.location.href="/login?reason=password-changed";return}setStatus(t.saved);router.refresh()}catch(err){setStatus(err instanceof Error?err.message:t.failed)}finally{setBusy(false)}}
 const rules=locale==="nl"?["12+ tekens","kleine letter","hoofdletter","cijfer","speciaal teken"]:locale==="de"?["12+ Zeichen","Kleinbuchstabe","Großbuchstabe","Zahl","Sonderzeichen"]:["12+ characters","lowercase letter","uppercase letter","number","special character"];
 return <main className="page settings-page"><section className="section"><div className="container settings-shell"><div className="settings-heading"><span className="eyebrow">{text.dashboard.account}</span><h1>{t.title}</h1><p>{t.intro}</p><Link href="/dashboard" className="text-link">← {t.back}</Link></div>
 <div className="settings-grid"><section className="settings-card"><h2>{t.profile}</h2><label>{t.name}<input value={name} onChange={e=>setName(e.target.value)} maxLength={80}/></label><label>{t.username}<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,""))} maxLength={30}/></label><button className="button button-primary" disabled={busy||name.trim().length<2||username.length<3} onClick={()=>requestCode("change_profile")}>{t.saveProfile}</button></section>
 <section className="settings-card"><h2>{t.password}</h2><label>{t.newPassword}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><div className="strength" data-score={pw.score}><div className="strength-line">{[0,1,2,3,4].map(i=><span key={i}/>)}</div><div className="password-rules">{rules.map((r,i)=><span key={r} data-ok={pw.checks[i]}>{pw.checks[i]?"✓":"○"} {r}</span>)}</div></div><label>{t.repeatPassword}<input type="password" value={repeat} onChange={e=>setRepeat(e.target.value)} autoComplete="new-password"/></label><button className="button button-primary" disabled={busy||!pw.valid||password!==repeat} onClick={()=>{if(password!==repeat){setStatus(t.passwordMismatch);return}requestCode("change_password")}}>{t.changePassword}</button></section>
 <section className="settings-card danger-settings"><h2>{t.delete}</h2><p>{t.deleteText}</p><button className="button danger-button solid" disabled={busy} onClick={()=>requestCode("delete_account")}>{t.deleteButton}</button></section></div><p className={`form-status ${status?"show":""}`} aria-live="polite">{status}</p></div></section>
 {action&&<div className="modal-backdrop"><div className="verify-modal settings-code-modal" role="dialog" aria-modal="true"><img className="modal-logo-mark" src="/assets/voidworks-mark.png" alt="Voidworks"/><span className="eyebrow">{t.sendCode}</span><h2>{t.verifyTitle}</h2><p>{t.verifyText} <strong>{email}</strong>. {t.codeHint}</p><form onSubmit={confirm}><div className="otp-boxes otp-six" onPaste={e=>{e.preventDefault();paste(e.clipboardData.getData("text"))}}>{digits.map((d,i)=><input key={i} ref={n=>{inputs.current[i]=n}} value={d} inputMode="numeric" maxLength={1} aria-label={`Code ${i+1}`} onChange={e=>digit(i,e.target.value)} onKeyDown={e=>key(i,e)}/>)}</div><button className="button button-primary" disabled={busy||digits.join("").length!==6}>{t.confirm}</button></form><div className="modal-actions"><button className="button button-secondary" type="button" onClick={()=>setAction(null)}>{t.cancel}</button><button className="text-button" type="button" onClick={()=>requestCode(action)}>{t.resend}</button></div></div></div>}
 </main>}
