"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";
import {copy,type Locale,type Theme} from "@/lib/i18n";
export type Consent="unset"|"essential"|"preferences";
type Preferences={locale:Locale;setLocale:(locale:Locale)=>void;theme:Theme;setTheme:(theme:Theme)=>void;consent:Consent;setConsent:(value:Exclude<Consent,"unset">)=>void;text:(typeof copy)[Locale]};
const Context=createContext<Preferences|null>(null);const YEAR=60*60*24*365;
function writeCookie(name:string,value:string,maxAge=YEAR){document.cookie=`${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; SameSite=Lax; Secure`}
export function PreferencesProvider({children,initialLocale="en",initialConsent="unset",initialTheme="dark"}:{children:React.ReactNode;initialLocale?:Locale;initialConsent?:Consent;initialTheme?:Theme}){const[locale,setLocaleState]=useState<Locale>(initialLocale);const[theme,setThemeState]=useState<Theme>(initialTheme);const[consent,setConsentState]=useState<Consent>(initialConsent);useEffect(()=>{const storedLocale=localStorage.getItem("voidworks-locale") as Locale|null;if(storedLocale&&["nl","en","de"].includes(storedLocale)&&storedLocale!==locale){setLocaleState(storedLocale);writeCookie("vw_locale",storedLocale)}const storedConsent=localStorage.getItem("voidworks-consent") as Consent|null;if(initialConsent==="unset"&&(storedConsent==="essential"||storedConsent==="preferences")){setConsentState(storedConsent);writeCookie("vw_consent",storedConsent)}if((initialConsent==="preferences"||storedConsent==="preferences")){const storedTheme=localStorage.getItem("voidworks-theme") as Theme|null;if(storedTheme==="dark"||storedTheme==="light")setThemeState(storedTheme)}},[]);useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dataset.theme=theme},[locale,theme]);const setLocale=(value:Locale)=>{setLocaleState(value);localStorage.setItem("voidworks-locale",value);writeCookie("vw_locale",value)};const setTheme=(value:Theme)=>{setThemeState(value);if(consent==="preferences"){localStorage.setItem("voidworks-theme",value);writeCookie("vw_theme",value)}};const setConsent=(value:Exclude<Consent,"unset">)=>{setConsentState(value);localStorage.setItem("voidworks-consent",value);writeCookie("vw_consent",value);if(value==="essential"){localStorage.removeItem("voidworks-theme");document.cookie="vw_theme=; Max-Age=0; Path=/; SameSite=Lax; Secure"}else{localStorage.setItem("voidworks-theme",theme);writeCookie("vw_theme",theme)}};const value=useMemo<Preferences>(()=>({locale,setLocale,theme,setTheme,consent,setConsent,text:copy[locale]}),[locale,theme,consent]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function usePreferences(){const c=useContext(Context);if(!c)throw new Error("usePreferences must be used inside PreferencesProvider");return c}
