import {createHmac,timingSafeEqual} from "crypto";
import {NextResponse} from "next/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {sendProjectMessageEmail} from "@/lib/email/resend";
import {ADMIN_EMAIL} from "@/lib/security/config";

function safeEqual(a:string,b:string){const x=Buffer.from(a);const y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)}
function verify(raw:string,request:Request){const secret=process.env.RESEND_WEBHOOK_SECRET||"";const id=request.headers.get("svix-id")||"";const timestamp=request.headers.get("svix-timestamp")||"";const signature=request.headers.get("svix-signature")||"";if(!secret||!id||!timestamp||!signature)return{ok:false,id};const unix=Number(timestamp);if(!Number.isFinite(unix)||Math.abs(Date.now()/1000-unix)>300)return{ok:false,id};try{const key=Buffer.from(secret.replace(/^whsec_/,""),"base64");const expected=createHmac("sha256",key).update(`${id}.${timestamp}.${raw}`).digest("base64");const valid=signature.split(/\s+/).some(part=>{const[,sig]=part.split(",",2);return Boolean(sig)&&safeEqual(sig,expected)});return{ok:valid,id}}catch{return{ok:false,id}}}
function emailAddress(value:string){const match=value.match(/<([^>]+)>/);return (match?.[1]||value).trim().toLowerCase()}
function plainFromHtml(html:string){return html.replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>/gi,"\n").replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&#39;/g,"'").replace(/&quot;/g,'"')}
function trimReply(value:string){let text=value.replace(/\r/g,"").trim();const cuts=[/\nOn .{0,200}wrote:\s*\n/i,/\nOp .{0,200}schreef.*:\s*\n/i,/\nAm .{0,200}schrieb.*:\s*\n/i,/\n-{2,}\s*Original Message\s*-{2,}/i];for(const re of cuts){const m=text.match(re);if(m?.index!==undefined)text=text.slice(0,m.index).trim()}text=text.split("\n").filter(line=>!line.trim().startsWith(">")).join("\n").trim();return text.slice(0,12000)}
async function getReceivedEmail(emailId:string){const key=process.env.RESEND_API_KEY;if(!key)throw new Error("RESEND_API_KEY missing");const r=await fetch(`https://api.resend.com/emails/receiving/${encodeURIComponent(emailId)}`,{headers:{Authorization:`Bearer ${key}`},cache:"no-store"});if(!r.ok)throw new Error("Received email fetch failed");return r.json() as Promise<{from:string;to:string[];text?:string|null;html?:string|null;subject?:string}>}
export async function POST(request:Request){const raw=await request.text();const checked=verify(raw,request);if(!checked.ok)return new NextResponse("Invalid webhook",{status:400});let event:any;try{event=JSON.parse(raw)}catch{return new NextResponse("Invalid payload",{status:400})}if(event.type!=="email.received")return NextResponse.json({ok:true});const admin=createAdminClient();const{error:dedupeError}=await admin.from("resend_webhook_events").insert({id:checked.id});if(dedupeError){if(String(dedupeError.code)==="23505")return NextResponse.json({ok:true,duplicate:true});return NextResponse.json({error:"DEDUPE_FAILED"},{status:500})}try{const emailId=String(event.data?.email_id||"");const received=await getReceivedEmail(emailId);const destination=(received.to||[]).find((item:string)=>/project[+-][0-9a-f-]{36}@/i.test(item));const match=destination?.match(/project[+-]([0-9a-f-]{36})@/i);if(!match)return NextResponse.json({ok:true,ignored:true});const projectId=match[1];const{data:project}=await admin.from("project_requests").select("id,requester_name,requester_email,company_name,locale").eq("id",projectId).maybeSingle();if(!project)return NextResponse.json({ok:true,ignored:true});const from=emailAddress(received.from||"");const adminSender=from===ADMIN_EMAIL;const clientSender=from===String(project.requester_email).toLowerCase();if(!adminSender&&!clientSender)return NextResponse.json({ok:true,ignored:true});const sourceText=String(received.text||"").trim()||plainFromHtml(String(received.html||""));const body=trimReply(sourceText);if(!body)return NextResponse.json({ok:true,ignored:true});const role=adminSender?"admin":"client";const{error}=await admin.from("project_messages").insert({project_id:projectId,sender_role:role,sender_email:from,body,source:"email",external_message_id:emailId});if(error&&String(error.code)!=="23505")throw error;if(adminSender)await sendProjectMessageEmail({to:project.requester_email,projectId,companyName:project.company_name,body,locale:project.locale||"en",senderName:"Voidworks"});else await sendProjectMessageEmail({to:ADMIN_EMAIL,projectId,companyName:project.company_name,body,locale:project.locale||"en",senderName:project.requester_name,adminNotification:true});return NextResponse.json({ok:true});}catch(error){try { await admin.from("resend_webhook_events").delete().eq("id",checked.id); } catch {}console.error(`[resend-inbound] ${error instanceof Error?error.message.slice(0,240):"failed"}`);return NextResponse.json({error:"WEBHOOK_FAILED"},{status:500})}}
