export type Locale = "nl" | "en" | "de";
export type Theme = "dark" | "light";

export const localeMeta = {
  nl: { label: "Nederlands", short: "NL", flag: "/assets/flags/nl.png" },
  en: { label: "English", short: "EN", flag: "/assets/flags/gb.png" },
  de: { label: "Deutsch", short: "DE", flag: "/assets/flags/de.png" },
} as const;

export const copy = {
  nl: {
    nav: { services: "Diensten", projects: "Projecten", process: "Werkwijze", pricing: "Prijzen", contact: "Contact", login: "Inloggen", register: "Registreren", dashboard: "Dashboard", discord: "Discord", start: "Project starten", language: "Taal", theme: "Weergave", dark: "Donker", light: "Licht" },
    hero: { title1: "Websites die je merk", title2: "serieus laten voelen.", text: "Design, development en onderhoud in één lijn. Donker, strak en gebouwd om snel en duidelijk te werken.", start: "Project starten", projects: "Bekijk projecten", speed: "Standaard websites meestal klaar in 2–4 werkdagen.", ai: "Door AI slim in te zetten voor repetitief ontwikkelwerk houden we de bouwtijd en prijs laag. Ontwerp, controle en oplevering blijven menselijk." },
    services: { kicker: "Diensten", title: "Wat we bouwen.", intro: "Geen overvolle templates. Alleen een sterke basis, goede details en functies die echt nodig zijn.", items: [
      ["Websites", "Snelle websites op maat met een sterke visuele stijl en een duidelijke focus op conversie."],
      ["Webapplicaties", "Dashboards, klantportalen en maatwerk functies wanneer een normale website niet genoeg is."],
      ["Redesign", "Bestaande websites opnieuw ontworpen en gebouwd zonder de uitstraling van een standaard template."],
      ["Hosting & onderhoud", "Deployments, updates en wijzigingen blijven geregeld nadat je website live staat."],
    ] },
    projects: { kicker: "Projecten", title: "Recent werk.", intro: "Verschillende merken met ieder een eigen stijl, structuur en doel.", community: "Community website", business: "Bedrijfswebsite", fentex: "Een duidelijke community-site met focus op navigatie, informatie en conversie.", flexwrap: "Een zakelijke website met een eigen identiteit, heldere structuur en sterke mobiele ervaring.", view: "Bekijk site ↗" },
    process: { kicker: "Werkwijze", title: "Van idee naar live.", intro: "Korte stappen, duidelijke feedbackmomenten en geen ingewikkeld proces.", items: [
      ["01", "Bespreken", "We bepalen wat de website moet doen, voor wie hij is en welke uitstraling daarbij past."],
      ["02", "Ontwerpen", "We zetten structuur, typografie, kleuren en interacties neer voordat de bouw begint."],
      ["03", "Bouwen", "De website wordt responsive gebouwd en getest op desktop, tablet en mobiel."],
      ["04", "Live", "Na de laatste feedback koppelen we je domein en zetten we de productieversie live."],
    ] },
    pricing: { kicker: "Prijzen", title: "Kies wat je nodig hebt.", intro: "Start met een pakket en voeg alleen de opties toe die echt bij je project passen.", extras: "Extra opties", complete: "Maak je pakket compleet.", completeText: "Alle keuzes hieronder zijn onderdeel van de site zelf. Niet beschikbaar voor dit pakket? Dan staat de optie duidelijk uitgeschakeld.", selected: "Geselecteerd", choose: "Kies pakket", popular: "Meest gekozen", included: "Inbegrepen", unavailable: "Niet beschikbaar", once: "Eenmalige indicatie", monthly: "Maandelijks", request: "Prijsaanvraag starten", note: "Indicatieve vanafprijzen excl. btw. Definitieve prijs volgt na scope en technische check.", from: "Vanaf", perMonth: "/mnd" },
    contact: { kicker: "Contact", title: "Klaar om iets sterks te bouwen?", intro: "Stuur kort wat je nodig hebt. Je hoeft nog geen compleet plan te hebben.", name: "Naam", email: "E-mail", subject: "Waar gaat het om?", message: "Vertel kort wat je nodig hebt", placeholderName: "Jouw naam", placeholderEmail: "naam@bedrijf.nl", placeholderMessage: "Wat wil je laten maken?", send: "Bericht versturen", sending: "Versturen...", success: "Verstuurd. We nemen zo snel mogelijk contact met je op.", select: "Kies een optie", options: ["Nieuwe website", "Prijsaanvraag", "Landing page", "Volledige website", "Webshop", "Website + admin panel", "Webplatform / API", "Website redesign", "Hosting / onderhoud", "Anders"] },
    auth: {
      area: "Klantomgeving", loginTitle: "Inloggen", loginText: "Log in om je projecten, status en accountgegevens te bekijken.", resetTitle: "Wachtwoord resetten", resetText: "We sturen een veilige resetlink naar je e-mailadres.", email: "E-mail", password: "Wachtwoord", passwordAgain: "Wachtwoord herhalen", show: "Tonen", hide: "Verbergen", forgot: "Wachtwoord vergeten?", login: "Inloggen", loggingIn: "Inloggen...", resetSend: "Resetlink sturen", sending: "Versturen...", back: "← Terug naar inloggen", noAccount: "Nog geen account?", makeAccount: "Account maken", registerTitle: "Account maken", registerText: "Maak je account aan. Daarna bevestig je je e-mail met de 6-cijferige code uit je mail.", name: "Naam", namePlaceholder: "Jouw naam", passwordPlaceholder: "Minimaal 12 tekens", repeatPlaceholder: "Herhaal je wachtwoord", creating: "Account maken...", haveAccount: "Heb je al een account?", strength: "Wachtwoordsterkte", empty: "Nog leeg", weak: "Zwak", fair: "Redelijk", strong: "Sterk", veryStrong: "Zeer sterk", need: "Nog nodig", rules: ["12+ tekens", "kleine letter", "hoofdletter", "cijfer", "speciaal teken"], match: "Wachtwoorden komen overeen", noMatch: "Wachtwoorden komen niet overeen", verifyEyebrow: "E-mail verificatie", verifyTitle: "Vul je 6-cijferige code in.", verifyText: "We hebben een verificatiecode gestuurd naar", codeSent: "Code verstuurd", verifyButton: "Code bevestigen", verifying: "Controleren...", resend: "Nieuwe code sturen", resendIn: "Nieuwe code over", changeEmail: "E-mailadres wijzigen", codeHint: "De code bestaat uit precies 6 cijfers en kan ook in één keer worden geplakt.", removed: "Je sessie is beëindigd omdat dit account niet meer bestaat." },
    dashboard: { eyebrow: "Dashboard", welcome: "Welkom terug", intro: "Hier vind je je projecten, status en accountgegevens.", projects: "Projecten", linked: "Aan je account gekoppeld", email: "E-mail", confirmed: "Bevestigd account", status: "Status", active: "Actief", secure: "Beveiligde klantomgeving", yourProjects: "Jouw projecten", noProject: "Nog geen project gekoppeld.", noProjectText: "Zodra we een project aan je account koppelen, verschijnt het hier automatisch.", start: "Project starten", account: "Account", accountDetails: "Accountgegevens", name: "Naam", verification: "Verificatie", verified: "Bevestigd", contact: "Contact opnemen", delete: "Account verwijderen", deleteTitle: "Account definitief verwijderen?", deleteText: "Dit verwijdert je Supabase Auth-account, profiel, sessie en gekoppelde projectdata. Daarna kun je hetzelfde e-mailadres opnieuw registreren.", cancel: "Annuleren", deleteConfirm: "Ja, account verwijderen", deleting: "Verwijderen..." },
    footer: { text: "Websites en webapplicaties op maat. Snel, duidelijk en betaalbaar door een slimme moderne workflow.", account: "Account", contact: "Contact", discord: "Discord", rights: "Voidworks" },
  },
  en: {
    nav: { services: "Services", projects: "Projects", process: "Process", pricing: "Pricing", contact: "Contact", login: "Log in", register: "Register", dashboard: "Dashboard", discord: "Discord", start: "Start a project", language: "Language", theme: "Appearance", dark: "Dark", light: "Light" },
    hero: { title1: "Websites that make your brand", title2: "feel serious.", text: "Design, development and maintenance in one line. Clean, fast and built to be clear.", start: "Start a project", projects: "View projects", speed: "Standard websites are usually ready within 2–4 working days.", ai: "By using AI intelligently for repetitive development work, we keep build time and pricing low. Design, review and delivery stay human." },
    services: { kicker: "Services", title: "What we build.", intro: "No overloaded templates. Just a strong foundation, good details and functions that are actually needed.", items: [["Websites", "Fast custom websites with a strong visual style and a clear focus on conversion."],["Web applications", "Dashboards, client portals and custom functions when a normal website is not enough."],["Redesign", "Existing websites redesigned and rebuilt without looking like a standard template."],["Hosting & maintenance", "Deployments, updates and changes remain managed after your website goes live."]] },
    projects: { kicker: "Projects", title: "Recent work.", intro: "Different brands, each with their own style, structure and goal.", community: "Community website", business: "Business website", fentex: "A clear community site focused on navigation, information and conversion.", flexwrap: "A business website with its own identity, clear structure and strong mobile experience.", view: "View site ↗" },
    process: { kicker: "Process", title: "From idea to live.", intro: "Short steps, clear feedback moments and no complicated process.", items: [["01", "Discuss", "We define what the website should do, who it is for and what style fits."],["02", "Design", "We set the structure, typography, colors and interactions before development starts."],["03", "Build", "The website is built responsively and tested on desktop, tablet and mobile."],["04", "Launch", "After final feedback we connect your domain and publish the production version."]] },
    pricing: { kicker: "Pricing", title: "Choose what you need.", intro: "Start with a package and add only the options that actually fit your project.", extras: "Extras", complete: "Complete your package.", completeText: "Every choice below uses custom site controls. If an option is not available for a package, it is clearly disabled.", selected: "Selected", choose: "Choose package", popular: "Most popular", included: "Included", unavailable: "Unavailable", once: "One-time estimate", monthly: "Monthly", request: "Start price request", note: "Indicative starting prices excluding VAT. Final price follows after scope and technical review.", from: "From", perMonth: "/mo" },
    contact: { kicker: "Contact", title: "Ready to build something strong?", intro: "Tell us briefly what you need. You do not need a complete plan yet.", name: "Name", email: "Email", subject: "What is it about?", message: "Tell us briefly what you need", placeholderName: "Your name", placeholderEmail: "name@company.com", placeholderMessage: "What would you like us to build?", send: "Send message", sending: "Sending...", success: "Sent. We will get back to you as soon as possible.", select: "Choose an option", options: ["New website", "Price request", "Landing page", "Full website", "Webshop", "Website + admin panel", "Web platform / API", "Website redesign", "Hosting / maintenance", "Other"] },
    auth: { area: "Client area", loginTitle: "Log in", loginText: "Log in to view your projects, status and account details.", resetTitle: "Reset password", resetText: "We will send a secure reset link to your email address.", email: "Email", password: "Password", passwordAgain: "Repeat password", show: "Show", hide: "Hide", forgot: "Forgot password?", login: "Log in", loggingIn: "Logging in...", resetSend: "Send reset link", sending: "Sending...", back: "← Back to login", noAccount: "No account yet?", makeAccount: "Create account", registerTitle: "Create account", registerText: "Create your account. Then confirm your email with the 6-digit code from your inbox.", name: "Name", namePlaceholder: "Your name", passwordPlaceholder: "At least 12 characters", repeatPlaceholder: "Repeat your password", creating: "Creating account...", haveAccount: "Already have an account?", strength: "Password strength", empty: "Empty", weak: "Weak", fair: "Fair", strong: "Strong", veryStrong: "Very strong", need: "Still needed", rules: ["12+ characters", "lowercase", "uppercase", "number", "special character"], match: "Passwords match", noMatch: "Passwords do not match", verifyEyebrow: "Email verification", verifyTitle: "Enter your 6-digit code.", verifyText: "We sent a verification code to", codeSent: "Code sent", verifyButton: "Verify code", verifying: "Checking...", resend: "Send new code", resendIn: "New code in", changeEmail: "Change email address", codeHint: "The code is exactly 6 digits and can also be pasted at once.", removed: "Your session ended because this account no longer exists." },
    dashboard: { eyebrow: "Dashboard", welcome: "Welcome back", intro: "Here you can find your projects, status and account details.", projects: "Projects", linked: "Linked to your account", email: "Email", confirmed: "Confirmed account", status: "Status", active: "Active", secure: "Secure client area", yourProjects: "Your projects", noProject: "No project linked yet.", noProjectText: "Once we link a project to your account, it will appear here automatically.", start: "Start a project", account: "Account", accountDetails: "Account details", name: "Name", verification: "Verification", verified: "Verified", contact: "Contact us", delete: "Delete account", deleteTitle: "Permanently delete account?", deleteText: "This removes your Supabase Auth account, profile, session and linked project data. You can then register the same email address again.", cancel: "Cancel", deleteConfirm: "Yes, delete account", deleting: "Deleting..." },
    footer: { text: "Custom websites and web applications. Fast, clear and affordable through a smart modern workflow.", account: "Account", contact: "Contact", discord: "Discord", rights: "Voidworks" },
  },
  de: {
    nav: { services: "Leistungen", projects: "Projekte", process: "Ablauf", pricing: "Preise", contact: "Kontakt", login: "Anmelden", register: "Registrieren", dashboard: "Dashboard", discord: "Discord", start: "Projekt starten", language: "Sprache", theme: "Ansicht", dark: "Dunkel", light: "Hell" },
    hero: { title1: "Websites, die deine Marke", title2: "ernst wirken lassen.", text: "Design, Entwicklung und Wartung aus einer Hand. Klar, schnell und sauber umgesetzt.", start: "Projekt starten", projects: "Projekte ansehen", speed: "Standard-Websites sind meist innerhalb von 2–4 Werktagen fertig.", ai: "Durch den gezielten Einsatz von KI für repetitive Entwicklungsarbeit halten wir Bauzeit und Preis niedrig. Design, Prüfung und Übergabe bleiben menschlich." },
    services: { kicker: "Leistungen", title: "Was wir bauen.", intro: "Keine überladenen Templates. Nur eine starke Basis, gute Details und Funktionen, die wirklich gebraucht werden.", items: [["Websites", "Schnelle individuelle Websites mit starkem visuellen Stil und klarem Fokus auf Conversion."],["Webanwendungen", "Dashboards, Kundenportale und individuelle Funktionen, wenn eine normale Website nicht reicht."],["Redesign", "Bestehende Websites neu gestaltet und gebaut, ohne wie ein Standard-Template auszusehen."],["Hosting & Wartung", "Deployments, Updates und Änderungen bleiben auch nach dem Launch geregelt."]] },
    projects: { kicker: "Projekte", title: "Aktuelle Arbeiten.", intro: "Unterschiedliche Marken mit jeweils eigener Gestaltung, Struktur und Zielsetzung.", community: "Community-Website", business: "Unternehmenswebsite", fentex: "Eine klare Community-Seite mit Fokus auf Navigation, Information und Conversion.", flexwrap: "Eine Unternehmenswebsite mit eigener Identität, klarer Struktur und starker mobiler Nutzung.", view: "Website ansehen ↗" },
    process: { kicker: "Ablauf", title: "Von der Idee zum Launch.", intro: "Kurze Schritte, klare Feedback-Momente und kein unnötig komplizierter Prozess.", items: [["01", "Besprechen", "Wir klären, was die Website tun soll, für wen sie gedacht ist und welcher Stil passt."],["02", "Entwerfen", "Wir legen Struktur, Typografie, Farben und Interaktionen fest, bevor die Entwicklung beginnt."],["03", "Bauen", "Die Website wird responsiv entwickelt und auf Desktop, Tablet und Mobilgerät getestet."],["04", "Live", "Nach dem letzten Feedback verbinden wir deine Domain und veröffentlichen die Produktionsversion."]] },
    pricing: { kicker: "Preise", title: "Wähle, was du brauchst.", intro: "Starte mit einem Paket und füge nur die Optionen hinzu, die wirklich zu deinem Projekt passen.", extras: "Extras", complete: "Vervollständige dein Paket.", completeText: "Alle Auswahlfelder gehören zur Website selbst. Nicht verfügbare Optionen werden klar deaktiviert.", selected: "Ausgewählt", choose: "Paket wählen", popular: "Beliebt", included: "Inklusive", unavailable: "Nicht verfügbar", once: "Einmalige Schätzung", monthly: "Monatlich", request: "Preisanfrage starten", note: "Unverbindliche Startpreise zzgl. MwSt. Der endgültige Preis folgt nach Scope- und Technikprüfung.", from: "Ab", perMonth: "/Monat" },
    contact: { kicker: "Kontakt", title: "Bereit, etwas Starkes zu bauen?", intro: "Sag uns kurz, was du brauchst. Ein vollständiger Plan ist noch nicht nötig.", name: "Name", email: "E-Mail", subject: "Worum geht es?", message: "Beschreibe kurz, was du brauchst", placeholderName: "Dein Name", placeholderEmail: "name@firma.de", placeholderMessage: "Was sollen wir für dich bauen?", send: "Nachricht senden", sending: "Wird gesendet...", success: "Gesendet. Wir melden uns so schnell wie möglich.", select: "Option wählen", options: ["Neue Website", "Preisanfrage", "Landingpage", "Komplette Website", "Webshop", "Website + Admin-Panel", "Webplattform / API", "Website-Redesign", "Hosting / Wartung", "Andere"] },
    auth: { area: "Kundenbereich", loginTitle: "Anmelden", loginText: "Melde dich an, um Projekte, Status und Kontodaten zu sehen.", resetTitle: "Passwort zurücksetzen", resetText: "Wir senden einen sicheren Reset-Link an deine E-Mail-Adresse.", email: "E-Mail", password: "Passwort", passwordAgain: "Passwort wiederholen", show: "Zeigen", hide: "Verbergen", forgot: "Passwort vergessen?", login: "Anmelden", loggingIn: "Anmelden...", resetSend: "Reset-Link senden", sending: "Senden...", back: "← Zurück zur Anmeldung", noAccount: "Noch kein Konto?", makeAccount: "Konto erstellen", registerTitle: "Konto erstellen", registerText: "Erstelle dein Konto und bestätige danach deine E-Mail mit dem 6-stelligen Code.", name: "Name", namePlaceholder: "Dein Name", passwordPlaceholder: "Mindestens 12 Zeichen", repeatPlaceholder: "Passwort wiederholen", creating: "Konto wird erstellt...", haveAccount: "Schon ein Konto?", strength: "Passwortstärke", empty: "Noch leer", weak: "Schwach", fair: "Mittel", strong: "Stark", veryStrong: "Sehr stark", need: "Noch nötig", rules: ["12+ Zeichen", "Kleinbuchstabe", "Großbuchstabe", "Zahl", "Sonderzeichen"], match: "Passwörter stimmen überein", noMatch: "Passwörter stimmen nicht überein", verifyEyebrow: "E-Mail-Bestätigung", verifyTitle: "Gib deinen 6-stelligen Code ein.", verifyText: "Wir haben einen Bestätigungscode gesendet an", codeSent: "Code gesendet", verifyButton: "Code bestätigen", verifying: "Prüfen...", resend: "Neuen Code senden", resendIn: "Neuer Code in", changeEmail: "E-Mail-Adresse ändern", codeHint: "Der Code besteht aus genau 6 Ziffern und kann komplett eingefügt werden.", removed: "Deine Sitzung wurde beendet, weil dieses Konto nicht mehr existiert." },
    dashboard: { eyebrow: "Dashboard", welcome: "Willkommen zurück", intro: "Hier findest du Projekte, Status und Kontodaten.", projects: "Projekte", linked: "Mit deinem Konto verknüpft", email: "E-Mail", confirmed: "Bestätigtes Konto", status: "Status", active: "Aktiv", secure: "Geschützter Kundenbereich", yourProjects: "Deine Projekte", noProject: "Noch kein Projekt verknüpft.", noProjectText: "Sobald wir ein Projekt mit deinem Konto verbinden, erscheint es hier automatisch.", start: "Projekt starten", account: "Konto", accountDetails: "Kontodaten", name: "Name", verification: "Bestätigung", verified: "Bestätigt", contact: "Kontakt aufnehmen", delete: "Konto löschen", deleteTitle: "Konto endgültig löschen?", deleteText: "Dadurch werden dein Supabase-Auth-Konto, Profil, deine Sitzung und verknüpfte Projektdaten gelöscht. Danach kannst du dieselbe E-Mail erneut registrieren.", cancel: "Abbrechen", deleteConfirm: "Ja, Konto löschen", deleting: "Wird gelöscht..." },
    footer: { text: "Individuelle Websites und Webanwendungen. Schnell, klar und bezahlbar durch einen modernen Workflow.", account: "Konto", contact: "Kontakt", discord: "Discord", rights: "Voidworks" },
  },
} as const;
