import type { Locale } from "@/lib/i18n";

export const portalCopy: Record<Locale, any> = {
  nl: {
    pricing:{choose:"Kies project",configure:"Kies je opties",continue:"Doorgaan met aanvraag",close:"Sluiten",included:"Inbegrepen",monthly:"per maand",once:"eenmalig",from:"Vanaf",selected:"Geselecteerd",extras:"Extra opties",summary:"Jouw selectie"},
    request:{eyebrow:"Projectaanvraag",title:"Vertel ons wat we gaan bouwen.",intro:"Vul de belangrijkste informatie in. Je ontvangt direct een bevestiging per mail en de aanvraag verschijnt automatisch in je account wanneer je met hetzelfde e-mailadres inlogt of registreert.",company:"Bedrijfsnaam",companyPlaceholder:"Naam van je bedrijf",companyDoes:"Wat doet het bedrijf?",companyDoesPlaceholder:"Beschrijf kort wat jullie doen, voor wie en wat belangrijk is.",siteType:"Wat voor site wil je?",siteTypePlaceholder:"Bijv. bedrijfswebsite, portfolio, webshop, klantportaal...",requirements:"Wat moet er op de site komen?",requirementsPlaceholder:"Pagina's, functies, formulieren, koppelingen, content, belangrijke onderdelen...",style:"Eventuele styleguide / stijlinspiratie",stylePlaceholder:"Kleuren, fonts, links naar voorbeelden of een korte omschrijving. Optioneel.",name:"Jouw naam",email:"E-mailadres",submit:"Project aanvragen",submitting:"Aanvraag versturen...",successTitle:"Project aangevraagd.",successText:"We hebben je aanvraag ontvangen en een bevestiging met alle gegevens naar je e-mailadres gestuurd.",dashboard:"Naar dashboard",register:"Account maken met dit e-mailadres",back:"Terug naar prijzen",invalid:"Controleer de ingevulde gegevens.",failed:"Aanvraag versturen is niet gelukt. Probeer het opnieuw.",security:"Voltooi eerst de beveiligingscontrole.",terms:"Door je aanvraag te versturen ga je akkoord met de voorwaarden en privacyverklaring.",price:"Prijsindicatie",package:"Pakket",addons:"Extra's",none:"Geen extra opties"},
    projects:{title:"Projecten",detail:"Projectdetails",requestId:"Aanvraag",status:"Status",requested:"Aangevraagd",company:"Bedrijf",package:"Pakket",requirements:"Wensen",style:"Stijl",conversation:"Berichten",reply:"Bericht sturen",replyPlaceholder:"Typ je bericht over dit project...",send:"Versturen",sending:"Versturen...",noMessages:"Nog geen berichten. Reacties van Voidworks verschijnen hier en worden ook per e-mail verstuurd.",back:"Terug naar dashboard",open:"Open project",created:"Aangevraagd op",messageFailed:"Bericht versturen is niet gelukt.",messageSent:"Bericht verstuurd.",start:"Nieuw project aanvragen"},
    settings:{title:"Accountinstellingen",intro:"Beheer je profiel, wachtwoord en account. Gevoelige wijzigingen bevestig je met een 6-cijferige code die 15 minuten geldig is.",profile:"Profiel",name:"Naam",username:"Gebruikersnaam",saveProfile:"Profiel wijzigen",password:"Wachtwoord",oldPassword:"Huidig wachtwoord",newPassword:"Nieuw wachtwoord",repeatPassword:"Wachtwoord herhalen",changePassword:"Wachtwoord wijzigen",delete:"Account verwijderen",deleteText:"Je login en persoonlijke accountgegevens worden verwijderd. Projectaanvragen kunnen bewaard blijven wanneer dit nodig is voor uitvoering, administratie of wettelijke verplichtingen.",deleteButton:"Verwijder account",sendCode:"Stuur verificatiecode",verifyTitle:"Bevestig met je code",verifyText:"We hebben een 6-cijferige code gestuurd naar",codeHint:"De code verloopt na 15 minuten en werkt één keer.",confirm:"Bevestigen",cancel:"Annuleren",resend:"Nieuwe code sturen",saved:"Wijziging opgeslagen.",profileSaved:"Profiel succesvol gewijzigd.",samePassword:"Je nieuwe wachtwoord mag niet hetzelfde zijn als je huidige wachtwoord.",currentPasswordIncorrect:"Je huidige wachtwoord is onjuist.",passwordChanged:"Wachtwoord gewijzigd. Je wordt opnieuw ingelogd via de loginpagina.",deleted:"Account verwijderd.",invalidCode:"De code is onjuist of verlopen.",failed:"De wijziging is niet gelukt.",usernameTaken:"Deze gebruikersnaam is al in gebruik.",passwordMismatch:"De wachtwoorden komen niet overeen.",back:"Terug naar dashboard"},
    forgot:{eyebrow:"Account herstellen",title:"Wachtwoord vergeten",intro:"Vul je e-mailadres in. Als het account bestaat sturen we een 6-cijferige code die 15 minuten geldig is.",email:"E-mail",send:"Code sturen",sending:"Versturen...",code:"6-cijferige code",newPassword:"Nieuw wachtwoord",repeat:"Wachtwoord herhalen",confirm:"Wachtwoord wijzigen",success:"Je wachtwoord is gewijzigd. Je kunt nu inloggen.",generic:"Als dit e-mailadres bestaat, is er een code verstuurd.",invalid:"De code is onjuist of verlopen.",failed:"Wachtwoord herstellen is niet gelukt.",back:"Terug naar inloggen"},
    admin:{users:"Gebruikers",projects:"Projectaanvragen",backups:"Back-ups",email:"E-mail",name:"Naam",created:"Aangemaakt",lastSignIn:"Laatste login",verified:"Bevestigd",open:"Open aanvraag",status:"Status",reply:"Reageren",replyPlaceholder:"Schrijf je reactie aan de klant...",send:"Reactie versturen",saveStatus:"Status opslaan",noProjects:"Nog geen projectaanvragen.",noUsers:"Geen gebruikers gevonden.",back:"Terug naar admin",requestData:"Aanvraaggegevens",client:"Klant",messages:"Berichten",sent:"Reactie verstuurd.",replyFailed:"Reactie versturen is niet gelukt.",statusFailed:"Status wijzigen is niet gelukt.",system:"Systeem"},
    mail:{projectSubject:"Je Voidworks projectaanvraag is ontvangen",adminSubject:"Nieuwe Voidworks projectaanvraag",replySubject:"Update over je Voidworks project",codeSubject:"Je Voidworks beveiligingscode"}
  },
  en: {
    pricing:{choose:"Choose project",configure:"Choose your options",continue:"Continue to request",close:"Close",included:"Included",monthly:"per month",once:"one-time",from:"From",selected:"Selected",extras:"Extra options",summary:"Your selection"},
    request:{eyebrow:"Project request",title:"Tell us what we should build.",intro:"Fill in the key information. You will immediately receive an email confirmation and the request will automatically appear in your account when you log in or register with the same email address.",company:"Company name",companyPlaceholder:"Your company name",companyDoes:"What does the company do?",companyDoesPlaceholder:"Briefly describe what you do, who it is for and what matters most.",siteType:"What kind of site do you want?",siteTypePlaceholder:"E.g. business website, portfolio, webshop, client portal...",requirements:"What should the site include?",requirementsPlaceholder:"Pages, features, forms, integrations, content, important sections...",style:"Optional style guide / visual inspiration",stylePlaceholder:"Colours, fonts, example links or a short description. Optional.",name:"Your name",email:"Email address",submit:"Request project",submitting:"Sending request...",successTitle:"Project requested.",successText:"We received your request and sent a confirmation with all details to your email address.",dashboard:"Go to dashboard",register:"Create an account with this email",back:"Back to pricing",invalid:"Check the information you entered.",failed:"The request could not be sent. Please try again.",security:"Complete the security check first.",terms:"By submitting your request you agree to the terms and privacy policy.",price:"Price indication",package:"Package",addons:"Extras",none:"No extra options"},
    projects:{title:"Projects",detail:"Project details",requestId:"Request",status:"Status",requested:"Requested",company:"Company",package:"Package",requirements:"Requirements",style:"Style",conversation:"Messages",reply:"Send message",replyPlaceholder:"Write a message about this project...",send:"Send",sending:"Sending...",noMessages:"No messages yet. Replies from Voidworks will appear here and are also sent by email.",back:"Back to dashboard",open:"Open project",created:"Requested on",messageFailed:"Could not send the message.",messageSent:"Message sent.",start:"Request a new project"},
    settings:{title:"Account settings",intro:"Manage your profile, password and account. Sensitive changes require a six-digit code that expires after 15 minutes.",profile:"Profile",name:"Name",username:"Username",saveProfile:"Change profile",password:"Password",oldPassword:"Current password",newPassword:"New password",repeatPassword:"Repeat password",changePassword:"Change password",delete:"Delete account",deleteText:"Your login and personal account data will be removed. Project requests may be retained where required for delivery, administration or legal obligations.",deleteButton:"Delete account",sendCode:"Send verification code",verifyTitle:"Confirm with your code",verifyText:"We sent a six-digit code to",codeHint:"The code expires after 15 minutes and works once.",confirm:"Confirm",cancel:"Cancel",resend:"Send new code",saved:"Change saved.",profileSaved:"Profile updated successfully.",samePassword:"Your new password cannot be the same as your current password.",currentPasswordIncorrect:"Your current password is incorrect.",passwordChanged:"Password changed. Please log in again.",deleted:"Account deleted.",invalidCode:"The code is incorrect or expired.",failed:"The change could not be completed.",usernameTaken:"This username is already in use.",passwordMismatch:"The passwords do not match.",back:"Back to dashboard"},
    forgot:{eyebrow:"Account recovery",title:"Forgot password",intro:"Enter your email. If the account exists, we will send a six-digit code valid for 15 minutes.",email:"Email",send:"Send code",sending:"Sending...",code:"6-digit code",newPassword:"New password",repeat:"Repeat password",confirm:"Change password",success:"Your password was changed. You can now log in.",generic:"If this email exists, a code has been sent.",invalid:"The code is incorrect or expired.",failed:"Password recovery failed.",back:"Back to login"},
    admin:{users:"Users",projects:"Project requests",backups:"Backups",email:"Email",name:"Name",created:"Created",lastSignIn:"Last login",verified:"Verified",open:"Open request",status:"Status",reply:"Reply",replyPlaceholder:"Write your reply to the client...",send:"Send reply",saveStatus:"Save status",noProjects:"No project requests yet.",noUsers:"No users found.",back:"Back to admin",requestData:"Request details",client:"Client",messages:"Messages",sent:"Reply sent.",replyFailed:"Could not send the reply.",statusFailed:"Could not update the status.",system:"System"},
    mail:{projectSubject:"Your Voidworks project request was received",adminSubject:"New Voidworks project request",replySubject:"Update about your Voidworks project",codeSubject:"Your Voidworks security code"}
  },
  de: {
    pricing:{choose:"Projekt wählen",configure:"Optionen wählen",continue:"Mit Anfrage fortfahren",close:"Schließen",included:"Inklusive",monthly:"pro Monat",once:"einmalig",from:"Ab",selected:"Ausgewählt",extras:"Zusatzoptionen",summary:"Deine Auswahl"},
    request:{eyebrow:"Projektanfrage",title:"Sag uns, was wir bauen sollen.",intro:"Trage die wichtigsten Informationen ein. Du erhältst sofort eine Bestätigung per E-Mail und die Anfrage erscheint automatisch in deinem Konto, wenn du dich mit derselben E-Mail anmeldest oder registrierst.",company:"Firmenname",companyPlaceholder:"Name deines Unternehmens",companyDoes:"Was macht das Unternehmen?",companyDoesPlaceholder:"Beschreibe kurz, was ihr macht, für wen und was wichtig ist.",siteType:"Welche Website möchtest du?",siteTypePlaceholder:"Z. B. Unternehmenswebsite, Portfolio, Webshop, Kundenportal...",requirements:"Was soll auf die Website?",requirementsPlaceholder:"Seiten, Funktionen, Formulare, Integrationen, Inhalte, wichtige Bereiche...",style:"Optionale Styleguide / Design-Inspiration",stylePlaceholder:"Farben, Fonts, Beispiel-Links oder kurze Beschreibung. Optional.",name:"Dein Name",email:"E-Mail-Adresse",submit:"Projekt anfragen",submitting:"Anfrage wird gesendet...",successTitle:"Projekt angefragt.",successText:"Wir haben deine Anfrage erhalten und eine Bestätigung mit allen Angaben per E-Mail gesendet.",dashboard:"Zum Dashboard",register:"Konto mit dieser E-Mail erstellen",back:"Zurück zu Preisen",invalid:"Überprüfe deine Angaben.",failed:"Die Anfrage konnte nicht gesendet werden. Bitte erneut versuchen.",security:"Schließe zuerst die Sicherheitsprüfung ab.",terms:"Mit dem Absenden stimmst du den Bedingungen und der Datenschutzerklärung zu.",price:"Preisindikation",package:"Paket",addons:"Extras",none:"Keine Zusatzoptionen"},
    projects:{title:"Projekte",detail:"Projektdetails",requestId:"Anfrage",status:"Status",requested:"Angefragt",company:"Unternehmen",package:"Paket",requirements:"Anforderungen",style:"Stil",conversation:"Nachrichten",reply:"Nachricht senden",replyPlaceholder:"Schreibe eine Nachricht zu diesem Projekt...",send:"Senden",sending:"Wird gesendet...",noMessages:"Noch keine Nachrichten. Antworten von Voidworks erscheinen hier und werden auch per E-Mail versendet.",back:"Zurück zum Dashboard",open:"Projekt öffnen",created:"Angefragt am",messageFailed:"Nachricht konnte nicht gesendet werden.",messageSent:"Nachricht gesendet.",start:"Neues Projekt anfragen"},
    settings:{title:"Kontoeinstellungen",intro:"Verwalte Profil, Passwort und Konto. Sensible Änderungen werden mit einem sechsstelligen Code bestätigt, der 15 Minuten gültig ist.",profile:"Profil",name:"Name",username:"Benutzername",saveProfile:"Profil ändern",password:"Passwort",oldPassword:"Aktuelles Passwort",newPassword:"Neues Passwort",repeatPassword:"Passwort wiederholen",changePassword:"Passwort ändern",delete:"Konto löschen",deleteText:"Login und persönliche Kontodaten werden gelöscht. Projektanfragen können gespeichert bleiben, wenn dies für Durchführung, Verwaltung oder gesetzliche Pflichten erforderlich ist.",deleteButton:"Konto löschen",sendCode:"Bestätigungscode senden",verifyTitle:"Mit Code bestätigen",verifyText:"Wir haben einen sechsstelligen Code gesendet an",codeHint:"Der Code läuft nach 15 Minuten ab und funktioniert einmal.",confirm:"Bestätigen",cancel:"Abbrechen",resend:"Neuen Code senden",saved:"Änderung gespeichert.",profileSaved:"Profil erfolgreich geändert.",samePassword:"Dein neues Passwort darf nicht mit deinem aktuellen Passwort identisch sein.",currentPasswordIncorrect:"Dein aktuelles Passwort ist falsch.",passwordChanged:"Passwort geändert. Bitte erneut anmelden.",deleted:"Konto gelöscht.",invalidCode:"Der Code ist falsch oder abgelaufen.",failed:"Die Änderung konnte nicht durchgeführt werden.",usernameTaken:"Dieser Benutzername ist bereits vergeben.",passwordMismatch:"Die Passwörter stimmen nicht überein.",back:"Zurück zum Dashboard"},
    forgot:{eyebrow:"Konto wiederherstellen",title:"Passwort vergessen",intro:"Gib deine E-Mail ein. Wenn das Konto existiert, senden wir einen sechsstelligen Code, der 15 Minuten gültig ist.",email:"E-Mail",send:"Code senden",sending:"Wird gesendet...",code:"6-stelliger Code",newPassword:"Neues Passwort",repeat:"Passwort wiederholen",confirm:"Passwort ändern",success:"Dein Passwort wurde geändert. Du kannst dich jetzt anmelden.",generic:"Wenn diese E-Mail existiert, wurde ein Code gesendet.",invalid:"Der Code ist falsch oder abgelaufen.",failed:"Passwort-Wiederherstellung fehlgeschlagen.",back:"Zurück zum Login"},
    admin:{users:"Benutzer",projects:"Projektanfragen",backups:"Backups",email:"E-Mail",name:"Name",created:"Erstellt",lastSignIn:"Letzter Login",verified:"Bestätigt",open:"Anfrage öffnen",status:"Status",reply:"Antworten",replyPlaceholder:"Schreibe deine Antwort an den Kunden...",send:"Antwort senden",saveStatus:"Status speichern",noProjects:"Noch keine Projektanfragen.",noUsers:"Keine Benutzer gefunden.",back:"Zurück zu Admin",requestData:"Anfragedaten",client:"Kunde",messages:"Nachrichten",sent:"Antwort gesendet.",replyFailed:"Antwort konnte nicht gesendet werden.",statusFailed:"Status konnte nicht aktualisiert werden.",system:"System"},
    mail:{projectSubject:"Deine Voidworks Projektanfrage ist eingegangen",adminSubject:"Neue Voidworks Projektanfrage",replySubject:"Update zu deinem Voidworks Projekt",codeSubject:"Dein Voidworks Sicherheitscode"}
  }
};

export const projectStatusLabels: Record<Locale, Record<string,string>> = {
  nl:{requested:"Aangevraagd",reviewing:"In beoordeling",accepted:"Geaccepteerd",building:"In ontwikkeling",waiting_for_client:"Wachten op klant",ready:"Klaar voor oplevering",live:"Live",cancelled:"Geannuleerd"},
  en:{requested:"Requested",reviewing:"Under review",accepted:"Accepted",building:"In development",waiting_for_client:"Waiting for client",ready:"Ready for delivery",live:"Live",cancelled:"Cancelled"},
  de:{requested:"Angefragt",reviewing:"In Prüfung",accepted:"Angenommen",building:"In Entwicklung",waiting_for_client:"Warten auf Kunde",ready:"Bereit zur Übergabe",live:"Live",cancelled:"Storniert"},
};
