import {NextResponse} from "next/server";
import {findAuthUserByEmail} from "@/lib/security/users";
import {issueAccountActionCode} from "@/lib/security/account-actions";
import {sendAccountSecurityCode} from "@/lib/email/resend";
import {consumeRateLimit} from "@/lib/security/rate-limit";
import {getClientIp,rejectCrossOrigin} from "@/lib/security/request";
import {verifyTurnstile} from "@/lib/security/bot";
const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export async function POST(request:Request){const cross=rejectCrossOrigin(request);if(cross)return cross;try{const body=await request.json() as Record<string,unknown>;const email=String(body.email||"").trim().toLowerCase().slice(0,160);const locale=body.locale==="nl"||body.locale==="de"?body.locale:"en";const turnstile=await verifyTurnstile(String(body.turnstileToken||""),"password_reset");if(!turnstile.ok)return NextResponse.json({error:turnstile.unavailable?"SECURITY_UNAVAILABLE":"BOT_CHECK_FAILED"},{status:turnstile.unavailable?503:403});if(!emailPattern.test(email))return NextResponse.json({ok:true});const ip=getClientIp(request);if(!(await consumeRateLimit(`password-reset:${ip}:${email}`,5,3600)))return NextResponse.json({error:"RATE_LIMIT"},{status:429});const user=await findAuthUserByEmail(email);if(user&&user.email){try{const code=await issueAccountActionCode(user,"password_reset");const label=locale==="nl"?"Gebruik deze code om je Voidworks-wachtwoord opnieuw in te stellen.":locale==="de"?"Nutze diesen Code, um dein Voidworks-Passwort zurückzusetzen.":"Use this code to reset your Voidworks password.";await sendAccountSecurityCode(user.email,code,locale,label);}catch(error){console.error(`[password-reset/email] ${error instanceof Error?error.message.slice(0,180):"failed"}`)}}return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}});}catch{return NextResponse.json({ok:true},{headers:{"Cache-Control":"no-store"}})}}
