import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {requireCsrf} from "@/lib/security/csrf";
import {rejectCrossOrigin} from "@/lib/security/request";
import {validateAppSession} from "@/lib/security/session";
import {consumeRateLimit} from "@/lib/security/rate-limit";
import {sendProjectMessageEmail} from "@/lib/email/resend";
import {ADMIN_EMAIL} from "@/lib/security/config";
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const cross=rejectCrossOrigin(request);if(cross)return cross;if(!(await requireCsrf(request)))return NextResponse.json({error:"CSRF"},{status:403});try{const{id}=await params;const body=await request.json() as{body?:string};const message=String(body.body||"").trim().slice(0,12000);if(!message)return NextResponse.json({error:"INVALID_INPUT"},{status:400});const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user||!user.email||!(await validateAppSession(user.id)))return NextResponse.json({error:"NOT_AUTHENTICATED"},{status:401});if(!(await consumeRateLimit(`project-message:${user.id}`,20,3600)))return NextResponse.json({error:"RATE_LIMIT"},{status:429});const admin=createAdminClient();const{data:project}=await admin.from("project_requests").select("id,user_id,requester_email,requester_name,company_name,locale").eq("id",id).maybeSingle();if(!project||project.user_id!==user.id)return NextResponse.json({error:"NOT_FOUND"},{status:404});const{error}=await admin.from("project_messages").insert({project_id:id,sender_role:"client",sender_email:user.email,body:message,source:"dashboard"});if(error)return NextResponse.json({error:"SAVE_FAILED"},{status:500});await sendProjectMessageEmail({to:ADMIN_EMAIL,projectId:id,companyName:project.company_name,body:message,locale:project.locale||"en",senderName:project.requester_name,adminNotification:true}).catch(err=>console.error(`[project-message/email] ${err instanceof Error?err.message.slice(0,160):"failed"}`));return NextResponse.json({ok:true});}catch{return NextResponse.json({error:"MESSAGE_FAILED"},{status:500})}}
